import express from 'express'
import { marked } from 'marked'
import { getConversationMessages, getAgentRunById, getOrCreateConversation } from '../services/supabase.js'
import { optionalAuth } from '../middleware/auth.js'

const router = express.Router()

// GET /api/export/pdf?mode=smart_chat
router.get('/pdf', optionalAuth, async (req, res, next) => {
  try {
    const { mode, runId } = req.query
    const userId = req.user?.id || 'demo'

    let htmlContent = ''
    let filename = 'finchatbot-export'

    if (runId) {
      // Export an agent run
      const run = await getAgentRunById(runId)
      if (!run) return res.status(404).json({ error: 'Agent run not found' })

      htmlContent = buildAgentRunHTML(run)
      filename = `finchatbot-agent-${new Date().toISOString().split('T')[0]}`
    } else {
      // Export a conversation
      const conversationId = await getOrCreateConversation(userId, mode || 'smart_chat')
      const messages = await getConversationMessages(conversationId, 100)

      if (!messages.length) return res.status(400).json({ error: 'No messages to export' })

      htmlContent = buildConversationHTML(messages, mode)
      filename = `finchatbot-${mode}-${new Date().toISOString().split('T')[0]}`
    }

    // Generate PDF from HTML using Puppeteer
    const pdf = await generatePDFFromHTML(htmlContent)

    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`)
    res.send(pdf)
  } catch (err) { next(err) }
})

// GET /api/export/markdown?mode=smart_chat
router.get('/markdown', optionalAuth, async (req, res, next) => {
  try {
    const { mode, runId } = req.query
    const userId = req.user?.id || 'demo'

    let markdownContent = ''
    let filename = 'finchatbot-export'

    if (runId) {
      const run = await getAgentRunById(runId)
      markdownContent = buildAgentRunMarkdown(run)
      filename = `finchatbot-agent-${new Date().toISOString().split('T')[0]}`
    } else {
      const conversationId = await getOrCreateConversation(userId, mode || 'smart_chat')
      const messages = await getConversationMessages(conversationId, 100)
      markdownContent = buildConversationMarkdown(messages, mode)
      filename = `finchatbot-${mode}-${new Date().toISOString().split('T')[0]}`
    }

    res.setHeader('Content-Type', 'text/markdown')
    res.setHeader('Content-Disposition', `attachment; filename="${filename}.md"`)
    res.send(markdownContent)
  } catch (err) { next(err) }
})

// ─── HTML BUILDERS ───────────────────────────────────────

function buildConversationHTML(messages, mode) {
  const modeLabels = {
    smart_chat: 'Smart Chat', document_analysis: 'Document Analysis',
    insights: 'Insights Mode', agentic: 'Agentic Mode',
  }
  const rows = messages.map(m => {
    const roleLabel = m.role === 'user' ? 'You' : 'FinChatBot'
    const roleColor = m.role === 'user' ? '#1D9E75' : '#378ADD'
    const citations = m.citations?.length
      ? `<div style="margin-top:8px">${m.citations.map(c => `<span style="font-size:11px;background:#f0f0f0;padding:2px 8px;border-radius:10px;margin-right:4px">[${c.file}, p.${c.page}]</span>`).join('')}</div>`
      : ''
    return `
      <div style="margin-bottom:20px;padding:14px;border-radius:8px;border:1px solid #e0e0e0">
        <div style="font-weight:600;color:${roleColor};margin-bottom:6px">${roleLabel}</div>
        <div style="font-size:14px;line-height:1.6;color:#333">${marked.parse(m.content)}</div>
        ${citations}
      </div>`
  }).join('')

  return `<!DOCTYPE html><html><head><meta charset="utf-8">
  <style>body{font-family:system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px;color:#111}
  h1{color:#0F6E56}h2{color:#333;border-bottom:1px solid #eee;padding-bottom:6px}</style></head>
  <body>
    <h1>FinChatBot Export</h1>
    <p style="color:#666">Mode: ${modeLabels[mode] || mode} &nbsp;|&nbsp; Date: ${new Date().toLocaleDateString('en-IN')}</p>
    <hr style="border:none;border-top:1px solid #eee;margin:20px 0">
    ${rows}
    <p style="color:#999;font-size:12px;margin-top:40px">Generated by FinChatBot — finchatbot.vercel.app</p>
  </body></html>`
}

function buildAgentRunHTML(run) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
  <style>body{font-family:system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px}
  h1{color:#0F6E56}.confidence{display:inline-block;background:#E1F5EE;color:#085041;padding:4px 12px;border-radius:12px;font-size:13px}</style></head>
  <body>
    <h1>FinChatBot Agent Report</h1>
    <p><strong>Goal:</strong> ${run.goal}</p>
    <p><strong>Date:</strong> ${new Date(run.created_at).toLocaleDateString('en-IN')}</p>
    <span class="confidence">Confidence: ${Math.round((run.confidence || 0.7) * 100)}%</span>
    <hr style="border:none;border-top:1px solid #eee;margin:20px 0">
    <div>${marked.parse(run.final_report || '')}</div>
    <p style="color:#999;font-size:12px;margin-top:40px">Generated by FinChatBot — finchatbot.vercel.app</p>
  </body></html>`
}

// ─── MARKDOWN BUILDERS ───────────────────────────────────

function buildConversationMarkdown(messages, mode) {
  const header = `# FinChatBot Export — ${mode}\n**Date:** ${new Date().toLocaleDateString('en-IN')}\n\n---\n\n`
  const footnotes = []
  const body = messages.map((m, i) => {
    const role = m.role === 'user' ? '**You**' : '**FinChatBot**'
    let text = `${role}\n\n${m.content}\n\n`
    if (m.citations?.length) {
      m.citations.forEach((c, j) => {
        const fn = footnotes.length + j + 1
        text += `[^${fn}]`
        footnotes.push(`[^${fn}]: ${c.file}, Page ${c.page}`)
      })
      text += '\n\n'
    }
    return text
  }).join('---\n\n')
  const footnotesText = footnotes.length ? '\n\n---\n\n' + footnotes.join('\n') : ''
  return header + body + footnotesText
}

function buildAgentRunMarkdown(run) {
  return `# FinChatBot Agent Report\n\n**Goal:** ${run.goal}\n**Date:** ${new Date(run.created_at).toLocaleDateString('en-IN')}\n**Confidence:** ${Math.round((run.confidence || 0.7) * 100)}%\n\n---\n\n${run.final_report || ''}`
}

// ─── PDF GENERATION ──────────────────────────────────────

async function generatePDFFromHTML(html) {
  let puppeteer
  try {
    puppeteer = await import('puppeteer')
  } catch {
    puppeteer = await import('puppeteer-core')
  }
  const browser = await puppeteer.default.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  })
  const page = await browser.newPage()
  await page.setContent(html, { waitUntil: 'networkidle0' })
  const pdf = await page.pdf({ format: 'A4', margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } })
  await browser.close()
  return pdf
}

export default router
